- name: client
  include:
    - client/**
- name: snrd
  include:
    - cmd/snrd/**
    - app/**
    - go.mod
    - go.sum
- name: devops
  include:
    - .github/**
    - .devcontainer/**
    - scripts/**
    - etc/**
    - Dockerfile
    - "*-compose.yml"
    - README.md
- name: docs
  include:
    - docs/**
- name: dex
  include:
    - proto/dex/**
    - x/dex/**
- name: did
  include:
    - proto/did/**
    - x/did/**
- name: dwn
  include:
    - proto/dwn/**
    - x/dwn/**
- name: svc
  include:
    - proto/svc/**
    - x/svc/**

