version: 2
project_name: sonr

# Only uncomment os, arch, and targets if you are NOT using cosmwasm / wasm-light-client.
# Windows, 386 (32bit), and ARM are not Wasm compatible.
builds:
  - id: core
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    main: ./cmd/sonrd
    binary: sonrd
    builder: go
    gobinary: go
    command: build
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: dwn
    goos:
      - js
    goarch:
      - wasm
    main: ./cmd/dwn/dwn.go
    binary: dwn
    builder: go
    gobinary: go
    command: build

  - id: motr
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/motrd
    binary: motrd
    builder: go
    gobinary: go
    command: build
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    builds:
      - core
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format: tar.gz
    files:
      - src: README*
      - src: CHANGELOG*

  - id: motr
    builds:
      - motr
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format: tar.gz
    files:
      - src: README*
      - src: CHANGELOG*

  - id: dwn
    builds:
      - dwn
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format: zip
    files:
      - src: CHANGELOG*
      - src: pkl/dwn.pkl

release:
  github:
    owner: onsonr
    name: sonr
  name_template: "{{.Tag}}"
  ids:
    - default
    - motr
    - dwn
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true

snapshot:
  name_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

source:
  name_template: "{{ .ProjectName }}-{{ .Version }}"
  format: tar.gz

git:
  tag_sort: -version:refname

github_urls:
  download: https://github.com

gitlab_urls:
  download: https://gitlab.com
