project_name: sonr

builds:
  - id: sonr
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/sonrd
    binary: sonrd
    builder: go
    gobinary: go
    command: build
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: motr
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/motr
    binary: motr
    builder: go
    gobinary: go
    command: build
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

  - id: dwn
    goos:
      - js
    goarch:
      - wasm
    main: ./cmd/dwn/dwn.go
    binary: dwn
    builder: go
    gobinary: go
    command: build

archives:
  - id: default
    builds:
      - sonr
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format: tar.gz
    files:
      - src: README*
      - src: CHANGELOG*

  - id: motr
    builds:
      - motr
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    format: tar.gz
    files:
      - src: README*
      - src: CHANGELOG*

release:
  github:
    owner: onsonr
    name: sonr
  name_template: "{{.Now.Format '2006.11.22'}}"
  ids:
    - default
    - motr
  draft: false
  replace_existing_draft: true
  replace_existing_artifacts: true
  extra_files:
    - glob: ./CHANGELOG*
    - glob: ./README*
    - glob: ./LICENSE*
    - glob: ./pkl/dwn.pkl

brews:
  - name: sonr
    ids:
      - default
      - motr
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    caveats: "Run a local sonr node and access it with the motr proxy"
    homepage: "https://sonr.io/"
    description: "Sonr is a decentralized, permissionless, and censorship-resistant identity network."
    dependencies:
      - name: ipfs
        os: mac
    repository:
      owner: onsonr
      name: homebrew-tap
      branch: master
