version: "0.6"

processes:
  air:
    namespace: testnet
    command: "devbox run serve:air"
    background: true
    availability:
      restart: on_failure
      max_restarts: 3

  sonr:
    namespace: testnet
    command: "devbox run serve:sonr"
    restart: on_failure
    max_restarts: 3
    depends:
