version: "0.6"

processes:
  ipfs:
    namespace: testnet
    command: "sh scripts/bootstrap_ipfs.sh"
    background: true
    availability:
      restart: on_failure
      max_restarts: 0

  sonr:
    namespace: testnet
    command: "make sh-testnet"
    restart: on_failure
    max_restarts: 1
    depends:
      - ipfs

  tunnel:
    namespace: public
    command: "devbox run start:tunnel"
    restart: on_failure
    max_restarts: 1
    depends:
      - caddy
