version: "0.6"

processes:
  ipfs:
    namespace: testnet
    command: "sh scripts/bootstrap_ipfs.sh"
    background: true
    availability:
      restart: on_failure
      max_restarts: 0

  sonr:
    namespace: testnet
    command: "make sh-testnet"
    restart: on_failure
    max_restarts: 3
    depends:
      - ipfs

  proxy:
    namespace: testnet
    command: "devbox run proxy"
    restart: on_failure
    max_restarts: 3
    depends:
      - sonr
