version: "3"

tasks:
  dev:
    cmd: air

  install:
    cmd: make install

  testnet:
    cmd: make sh-testnet

  proto:
    cmd: devbox -q run proto

  build:sonrd:
    cmd: go build -o ./bin/sonrd ./cmd/sonrd
