#
version: '3'
includes:
  buf: .github/taskfiles/Buf.yml
  bun: .github/taskfiles/Bun.yml
  docker: .github/taskfiles/Docker.yml
  dokku: .github/taskfiles/Dokku.yml
  doppler: .github/taskfiles/Doppler.yml
  gh: .github/taskfiles/Gh.yml
  go: .github/taskfiles/Go.yml
  goreleaser: .github/taskfiles/Goreleaser.yml
  log: .github/taskfiles/Log.yml
  pkl: .github/taskfiles/Pkl.yml
  templ: .github/taskfiles/Templ.yaml
  wrangler: .github/taskfiles/Wrangler.yml

silent: true
vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
