version: "3"

tasks:
  dev:
    cmd: air

  install:
    cmd: make install

  testnet:
    cmd: make sh-testnet

  proto:
    cmd: devbox -q run proto

  templ:
    cmd: templ generate

  build:vltd:
    cmd: go build -o ./bin/vltd ./cmd/vltd

  build:sonrd:
    cmd: go build -o ./bin/sonrd ./cmd/sonrd

  build:dwn:
    cmd: tinygo build -o ./bin/dwn.wasm -target wasi ./internal/dwn/db.go
