# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
---
version: 2
dist: dist/hway
monorepo:
  tag_prefix: hway/
  dir: cmd/hway

project_name: hway

before:
  hooks:
    - go mod download

builds:
  # Hway Darwin AMD64
  - id: hway-darwin-amd64
    main: .
    binary: hway
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -s -w # Strip debug info

  # Hway Darwin ARM64
  - id: hway-darwin-arm64
    main: .
    binary: hway
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -s -w # Strip debug info

  # Hway Linux AMD64
  - id: hway-linux-amd64
    main: .
    binary: hway
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -s -w

  # Hway Linux ARM64
  - id: hway-linux-arm64
    main: .
    binary: hway
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -s -w

aurs:
  - name: hway-bin
    disable: true
    homepage: "https://sonr.io"
    description: "Highway service - bridge between the Public Internet and Sonr blockchain"
    maintainers:
      - "Sonr <support@sonr.io>"
    license: "Apache-2.0"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://[email protected]/hway-bin.git"
    skip_upload: auto
    provides:
      - hway
    conflicts:
      - hway
    depends:
      - redis
    optdepends:
      - "docker: for container-based vault operations"
    commit_msg_template: "Update to {{ .Tag }}"
    commit_author:
      name: goreleaserbot
      email: "prad@sonr.io"
    package: |-
      # bin
      install -Dm755 "./hway" "${pkgdir}/usr/bin/hway"

      # license
      if [ -f "./LICENSE" ]; then
        install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/hway-bin/LICENSE"
      fi

      # readme
      if [ -f "./README.md" ]; then
        install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/hway-bin/README.md"
      fi

      # systemd service (if exists)
      if [ -f "./hway.service" ]; then
        install -Dm644 "./hway.service" "${pkgdir}/usr/lib/systemd/system/hway.service"
      fi

nix:
  - name: hway
    ids:
      - hway
    homepage: "https://sonr.io"
    description: "Highway network component for Sonr"
    license: "gpl3Plus"
    path: pkgs/hway/default.nix
    commit_msg_template: "hway: {{ .Tag }}"
    dependencies:
      - stdenv
      - glibc
    extra_install: |-
      wrapProgram $out/bin/hway --prefix PATH : ${lib.makeBinPath [ glibc stdenv.cc.cc.lib ]}
    repository:
      owner: sonr-io
      name: nur
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"

archives:
  - id: hway
    ids:
      - hway-linux-amd64
      - hway-linux-arm64
      - hway-darwin-amd64
      - hway-darwin-arm64
    name_template: >-
      hway_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }}
    formats: ["tar.gz"]
    files:
      - src: README*
    wrap_in_directory: false

nfpms:
  - id: hway
    package_name: hway
    ids:
      - hway-linux-amd64
      - hway-linux-arm64
    file_name_template: "hway_{{ .Os }}_{{ .Arch }}{{ .ConventionalExtension }}"
    vendor: Sonr
    homepage: "https://sonr.io"
    maintainer: "Sonr <support@sonr.io>"
    description: "Hway is the bridge between the Public Internet and the Sonr blockchain."
    license: "Apache 2.0"
    formats:
      - rpm
      - deb
      - apk
      - archlinux
    contents:
      - src: README*
        dst: /usr/share/doc/hway
    bindir: /usr/bin
    section: net
    priority: optional

blobs:
  - provider: s3
    endpoint: https://eb37925850388bca807b7fab964c12bb.r2.cloudflarestorage.com
    bucket: releases
    region: auto
    directory: "hway/{{ .Tag }}"
    ids:
      - hway

release:
  disable: false
  github:
    owner: sonr-io
    name: sonr
  name_template: "{{.ProjectName}}/{{ .Tag }}"
  draft: false
  replace_existing_draft: false  # Don't replace drafts
  replace_existing_artifacts: false  # Append, don't replace
  mode: append  # Explicitly set to append mode

checksum:
  name_template: 'hway_checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

# Changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
