[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# Network configurations
[rpc_endpoints]
sonr = "${SONR_RPC_URL}"
sonr_testnet = "${SONR_TESTNET_RPC_URL}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
sonr = { key = "${ETHERSCAN_API_KEY}" }

# Testing configuration
[fuzz]
runs = 256

[invariant]
runs = 256
depth = 128
fail_on_revert = false
