name: Bug Report
description: File a bug report.
title: "ERROR: "
labels: ["#BUG", "#HELP"]
projects: ["onsonr/39"]
body:
  - type: textarea
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "Example: macOS Big Sur"
      value: operating system
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Network
      description: What network are you using?
      multiple: false
      options:
        - LocalNet
        - TestNet
        - MainNet
      default: 0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](link/to/coc)
          required: true
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
