name: Tracking issue
description: Use this template for tracking new features.
title: "(v0.6): FEATURE NAME"
labels: ["OKR"]
projects: ["onsonr/37"]
body:
  - type: checkboxes
    attributes:
      label: Is this associated with a milestone?
      description: This is a tracking issue for tracking a new feature for a given milestone.
      options:
        - label: I have confirmed this is an OKR tracking issue
          required: true
  - type: textarea
    attributes:
      label: Objective
      description: Explain the objective of the feature.
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Task List
      description: |
        Break down of tasks to complete the objective.
      value: |
        - [ ] Task 1
        - [ ] Task 2
        - [ ] Task 3
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Resources
      description: |
        Provide additional context relevant to the feature.
    validations:
      required: false
