version: "0.6"

processes:
  sonr:
    namespace: testnet
    command: "devbox run serve:sonr"
    restart: on_failure
    max_restarts: 3
    depends:

  caddy:
    namespace: testnet
    command: "devbox run serve:xcaddy"
    restart: on_failure
    max_restarts: 3
    depends:
      - sonr

  air:
    namespace: testnet
    command: "devbox run serve:air"
    restart: on_failure
    max_restarts: 3
    depends:
      - sonr
