version: "2"
sql:
  - engine: "sqlite"
    queries: "./sink/query_vault.sql"
    schema: "./sink/schema_vault.sql"
    gen:
      go:
        package: "orm"
        out: "../pkg/vault/orm"

  - engine: "postgresql"
    queries: "./sink/query_highway.sql"
    schema: "./sink/schema_highway.sql"
    gen:
      go:
        package: "orm"
        out: "../pkg/gateway/orm"
        sql_package: "pgx/v5" 

