main = ".open-next/worker.js"
name = "highway-dash"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 3200

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Development environment (default)
[env.development]
# Add any development-specific environment variables here

# Production environment
[env.production]
# Add any production-specific environment variables here

# Build configuration is handled separately by opennextjs-cloudflare
[build]
command = "opennextjs-cloudflare build"
cwd = "."

# Analytics and observability
[observability]
enabled = true
