// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file ibc/core/client/v2/query.proto (package ibc.core.client.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryConfigRequest, QueryConfigResponse, QueryCounterpartyInfoRequest, QueryCounterpartyInfoResponse } from "./query_pb.js";

const TYPE_NAME = "ibc.core.client.v2.Query";

/**
 * CounterpartyInfo queries an IBC light counter party info.
 *
 * @generated from rpc ibc.core.client.v2.Query.CounterpartyInfo
 */
export const QueryCounterpartyInfoService = {
  typeName: TYPE_NAME,
  method: "CounterpartyInfo",
  Request: QueryCounterpartyInfoRequest,
  Response: QueryCounterpartyInfoResponse,
} as const;

/**
 * Config queries the IBC client v2 configuration for a given client.
 *
 * @generated from rpc ibc.core.client.v2.Query.Config
 */
export const QueryConfigService = {
  typeName: TYPE_NAME,
  method: "Config",
  Request: QueryConfigRequest,
  Response: QueryConfigResponse,
} as const;

