// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file ibc/core/client/v2/tx.proto (package ibc.core.client.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgRegisterCounterparty, MsgRegisterCounterpartyResponse, MsgUpdateClientConfig, MsgUpdateClientConfigResponse } from "./tx_pb.js";

const TYPE_NAME = "ibc.core.client.v2.Msg";

/**
 * RegisterCounterparty defines a rpc handler method for MsgRegisterCounterparty.
 *
 * @generated from rpc ibc.core.client.v2.Msg.RegisterCounterparty
 */
export const MsgRegisterCounterpartyService = {
  typeName: TYPE_NAME,
  method: "RegisterCounterparty",
  Request: MsgRegisterCounterparty,
  Response: MsgRegisterCounterpartyResponse,
} as const;

/**
 * UpdateClientConfig defines a rpc handler method for MsgUpdateClientConfig.
 *
 * @generated from rpc ibc.core.client.v2.Msg.UpdateClientConfig
 */
export const MsgUpdateClientConfigService = {
  typeName: TYPE_NAME,
  method: "UpdateClientConfig",
  Request: MsgUpdateClientConfig,
  Response: MsgUpdateClientConfigResponse,
} as const;

