
version: "3"

vars:
  GOPATH:
    sh: go env GOPATH
  BIN_DIR: "{{.GOPATH}}/bin"
  BINARY: "{{.BIN_DIR}}/hway"
  OS:
    sh: uname -s
  ARCH:
    sh: uname -m

tasks:
  proto:
    desc: Generate proto files
    silent: true
    cmd: gum spin --spinner dot --title "Generating Protobufs..." -- make proto-gen

  sqlc:
    desc: Generate SQLC files
    silent: true
    cmds:
      - gum spin --spinner dot --title "Generating SQLC..." -- sqlc generate -f internal/database/sqlc.yaml

  templ:
    desc: Generate templ files
    silent: true
    cmd: gum spin --spinner dot --title "Generating Templ..." -- templ generate


