version: '3'

tasks:
  logi-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - gum log -l info {{.TEXT}}

  logw-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - gum log -l warn {{.TEXT}}

  loge-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - gum log -l error {{.TEXT}}

  logd-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - gum log -l debug {{.TEXT}}
