version: "3"

vars:
  ROOT:
    sh: git rev-parse --show-toplevel

tasks:
  build:
    desc: Build all matrix docker images
    cmds:
      - task: docker-build-push
        vars:
          DOCKER_FILE: deploy/matrixhs/server.Dockerfile
          DOCKER_IMAGE: onsonr/synapse
      - task: docker-build-push
        vars:
          DOCKER_FILE: deploy/matrixhs/hooks.Dockerfile
          DOCKER_IMAGE: onsonr/hookshot
      - task: docker-build-push
        vars:
          DOCKER_FILE: deploy/matrixhs/sync.Dockerfile
          DOCKER_IMAGE: onsonr/sliding-sync
      - task: docker-build-push
        vars:
          DOCKER_FILE: deploy/matrixhs/web.Dockerfile
          DOCKER_IMAGE: onsonr/element-web
    silent: true

  docker-build-push:
    internal: true
    vars:
      required: [DOCKER_FILE, DOCKER_IMAGE]
    cmds:
      - docker build -t {{.DOCKER_IMAGE}}:latest -f {{.DOCKER_FILE}} .
      - docker build -t {{.DOCKER_IMAGE}}:{{.COMMIT}} -f {{.DOCKER_FILE}} .
      - docker push {{.DOCKER_IMAGE}}:latest
      - docker push {{.DOCKER_IMAGE}}:{{.COMMIT}}
