version: "3"

vars:
  GOPATH:
    sh: go env GOPATH
  BIN_DIR: "{{.GOPATH}}/bin"
  OS:
    sh: uname -s
  ARCH:
    sh: uname -m

tasks:
  init-pkl:
    desc: Configure synapse homeserver with PKL
    silent: true
    cmds:
      - pkl eval pkl/matrix.net/Homeserver.pkl -f yaml -o deploy/conf/synapse/homeserver.yaml
    env:
      MATRIX_CLIENT_NAME: sonr.id
      MATRIX_SERVER_NAME: sonr.id
      MATRIX_SERVER_URL: http://localhost:8008
      MATRIX_SLIDING_SYNC_PROXY: http://localhost:8008
      MATRIX_PSQL_CONN: postgresql://matrixhs_user:matrixhs_password123@localhost:5432/sonr
      MATRIX_REGISTRATION_SHARED_SECRET: secret
      MATRIX_ENABLE_RECATCHA: false
      MATRIX_RECATCHA_PUBLIC_KEY: ""
      MATRIX_RECATCHA_PRIVATE_KEY: ""
      MATRIX_RECATCHA_BYPASS_SECRET: ""

