version: "3"

vars:
  GOPATH:
    sh: go env GOPATH
  OS:
    sh: uname -s
  ARCH:
    sh: uname -m

tasks:
  install-go:
    desc: Install go dependencies
    silent: true
    vars:
      DEPS:
        [
          "github.com/apple/pkl-go/cmd/pkl-gen-go@latest",
          "github.com/sqlc-dev/sqlc/cmd/sqlc@latest",
          "github.com/goreleaser/goreleaser/v2@latest",
          "github.com/a-h/templ/cmd/templ@latest",
        ]
    cmds:
      - for: { var: DEPS }
        cmd: gum spin --spinner dot --title "Installing go dependencies..." -- go install {{.ITEM}}


