version: '3'

tasks:
  info-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - gum log -l info {{.TEXT}}

  warn-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - gum log -l warn {{.TEXT}}

  error-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - gum log -l error {{.TEXT}}

  debug-*:
    vars:
      TEXT: '{{index .MATCH 0}}'
    cmds:
      - gum log -l debug {{.TEXT}}
