name: Deploy Networks
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - develop
      - feature/*

permissions:
  contents: write
  issues: write

jobs:
  reboot-devnet:
    name: Devnet Deploy
    runs-on: goliath
    environment: "Devnet"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch latest changes
        run: git fetch --prune --unshallow

      - name: Stop Devnet
        continue-on-error: true
        run: |
          make stop

      - name: Start Devnet
        run: |
          make start
