name: Deploy Network
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - develop
      - feature/*

permissions:
  contents: write
  issues: write

jobs:
  devnet_restart:
    name: Restart Devnet
    runs-on: goliath
    environment: "Devnet"
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v3
      - name: Restart Devnet
        run: |
          make restart
