name: Deploy Networks
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    branches:
      - develop
      - feature/*

permissions:
  contents: write
  issues: write

jobs:
  reboot-devnet:
    name: Devnet Deploy
    runs-on: goliath
    environment: "Devnet"
    steps:
      - name: Stop Devnet
        continue-on-error: true
        run: |
          cd ~/ghq/github.com/onsonr/sonr && make stop
      - name: Start Devnet
        run: |
          cd ~/ghq/github.com/onsonr/sonr && make start
