name: Post Release
on:
  release:
    types: [published]

permissions:
  contents: write
  issues: write

jobs:
  buf_push:
    name: Publish Protobufs
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4
      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1
      # Push only the Input in `proto` to the BSR
      - uses: bufbuild/buf-push-action@v1
        continue-on-error: true
        with:
          input: proto
          buf_token: ${{ secrets.BUF_TOKEN }}

  container-push:
    name: Publish Dockers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/onsonr/sonr:latest
