name: Automatic Tag Bump
on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      - master

permissions:
  contents: write

jobs:
  create_release_tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Commitizen
        run: pip install commitizen

      - name: Determine next version
        id: version
        run: |
          next_version=$(cz bump --dry-run)
          echo "Next version: $next_version"
          echo "NEW_VERSION=$next_version" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a "release/${{ env.NEW_VERSION }}" -m "Release ${{ env.NEW_VERSION }}"
          git push origin "release/${{ env.NEW_VERSION }}"
