name: Bump version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GH_PAT_TOKEN }}"
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true

      - name: Run tests
        run: make test

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GH_PAT_TOKEN }}
